console.log("This Is My First Assignment I Perform Today");
var message = "Hey Abu Huraiirah,I Have Started Learning TYPESCRIPT";
console.log(message);
var Name = "My Name Is Muhammad Ibrahim";
console.log(Name);
console.log("sum of numbers");
var x1 = 1;
var x2 = 2;
var x3 = 3;
var x4 = 4;
var x5 = 5;
var x6 = 6;
var x7 = 7;
var x8 = 8;
var x9 = 9;
var x10 = 10;
var y1 = (x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9 + x10);
console.log(y1);
console.log("After Apply Multiply");
var y2 = (x1 * x2 * x3 * x4 * x5 * x6 * x7 * x8 * x9 * x10);
console.log(y2);
console.log("After Apply Sutraction");
var y3 = (x1 - x2 - x3 - x4 - x5 - x6 - x7 - x8 - x9 - x10);
console.log(y3);
console.log("After Apply Division");
var x11 = 8;
var x12 = 2;
var result = x11 / x12;
console.log(result);
